version: '3.6'
services: 
  mysqldb:
      image: mysql:5.7.22
      environment:
          MYSQL_PASSWORD: root
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: datosVarios
      networks:
            - sensores-service
      restart: always
      volumes:
        - ./data:/var/lib/mysql
  rabbitmq:
        image: rabbitmq:3-management
        command: "/bin/bash -c \"rabbitmq-plugins enable rabbitmq_mqtt; rabbitmq-server\""
        ports:
            - "15672:15672"
            - "5672:5672"
            - "1883:1883"
        networks:
            - sensores-service
  service:
        image: elbatu/sensores:latest
        restart: on-failure
        ports:
            - "8081:8081"
        environment:
            cola: uno
        networks:
            - sensores-service     
networks:
  sensores-service:
